model_name: microsoft/codebert-base
max_length: 512
vulnerability_types:
  # Rust-specific vulnerabilities
  - unsafe_code
  - integer_overflow
  - integer_underflow
  - panic_handling
  - memory_leak
  - use_after_free
  - buffer_overflow
  - null_pointer
  - double_free
  - format_string
  - race_condition
  - deadlock
  - resource_exhaustion
  - infinite_loop
  - stack_overflow
  # Solana-specific vulnerabilities
  - account_validation
  - program_derivation
  - seed_validation
  - signature_verification
  - instruction_validation
  - data_validation
  - authority_validation
  - rent_exemption
  - account_lamports
  - program_ownership
  - cross_program_invocation
  - syscall_validation
  - token_program
  - associated_token
  - pda_validation
severity_mapping:
  critical: 1.0
  high: 0.8
  medium: 0.5
  low: 0.2
mitigation_strategies:
  reentrancy: "Use checks-effects-interactions, reentrancy guards."
  integer_overflow: "Use SafeMath/checked arithmetic."
  access_control: "Apply role-based access control, onlyOwner guards."

